### ISSUE TITLE
Calling throng relaunches index.js oO

### ISSUE THREAD

**Issue by cyrilchapon** [hunterloftis/throng#30]
Without throng
```
const myFunc = () => { console.log('world') }
console.log('Hello')
myFunc()

// hello
// world
```

With throng (1)
```
const throng = require('throng')
const myFunc = () => { console.log('world') }
console.log('hello')
throng(1, myFunc)

// hello
// hello
// world
```

With throng (5)
```
const throng = require('throng')
const myFunc = () => { console.log('world') }
console.log('hello')
throng(5, myFunc)

// hello
// hello
// hello
// world
// world
// hello
// world
// hello
// world
// hello
// world
```

What the ... ?

**Comment by douglascayers** [comment]
Hi @cyrilchapon,

This is expected and is the behavior of Nodejs [Cluster](https://nodejs.org/api/cluster.html#cluster_cluster) API. I'll explain.

When throng runs the [cluster.fork()](https://github.com/hunterloftis/throng/blob/master/lib/throng.js#L48) function, Nodejs spawns a new process that executes the current file in the newly spawned process.

This is why with 1 worker you see the following output:

```
// index.js
1. const throng = require('throng')
2. const myFunc = () => { console.log('world') }
3. console.log('hello')
4. throng(1, myFunc)

// hello
// hello
// world
```

## What's Happening

1. You run `node index.js` and the first process is started and executes your file.
2. At line 3, `console.log('hello')`, you see your first "hello" printed.
3. At line 4, `throng(1, myFunc)` runs. In throng at line 24 the expression [if (cluster.isWorker)](https://github.com/hunterloftis/throng/blob/master/lib/throng.js#L24) is `false` so throng runs the rest of its logic. Importantly, its lines 36 then 48 which calls `cluster.fork()`. At that point, Node.js creates a **new** process. You can think of it like Nodejs just did a second `node index.js`. There are now two copies of `index.js` being run by Nodejs. The difference is that in this spawned process, `cluster.isWorker` will be `true`.
4. In this spawned process of your `index.js`, your line 3 runs again and you see the second "hello" printed.
5. At line 4, `throng(1, myFunc)` runs. This time, however, since we are already in a spawned process (Nodejs knows this), then at line 24 the expression [if (cluster.isWorker)](https://github.com/hunterloftis/throng/blob/master/lib/throng.js#L24) is `true` so instead of forking another spawned process throng instead runs the worker function you passed in, `myFunc`. That is when you see "world" printed.

**Comment by FalconPilot** [comment]
@douglascayers 
Your answer, alas, does not take into account the NodeJS cluster documentation.

Infering the callee as being the cluster's entrypoint is very dangerous if it isn't :

- Documented
- Possible to be configured

Which is the case with Throng. In the [cluster documentation](https://nodejs.org/api/cluster.html#cluster_cluster_settings), it is specified that the argument `cluster.exec` is used to specify which NodeJS file will be the entrypoint for workers, and the default value for that is `process.argv[1]` which, indeed, ends up being the main NodeJS entrypoint. This violates pretty much everything the cluster API is designed for, which here is "setting up a cluster entrypoint which is able to spawn sub-workers".

I will admit it that setting `process.argv[1]` as a default value for the worker process entrypoint is a weird design choice IMHO, but that's not the point. I'm just explaining why in my opinion the impossibility to configure Throng's worker entrypoints is not a good idea.

A master process and a worker process should be able to have two separate entrypoints, which is possible with a vanilla Cluster implementation, and impossible with Throng, which makes it, IMHO, a pretty critical flaw that could be very easily fixed.

**Comment by douglascayers** [comment]
Thanks @FalconPilot 

My reply was just to explain why @cyrilchapon was seeing the output that he saw based on how Throng was implemented. 

I’m not a maintainer of this project, just saw the question. :)

**Comment by FalconPilot** [comment]
@douglascayers My mistake ! :)
Though I do think Throng could benefit (and should definitely) at least be updated to implement configuration of the entrypoint. I might make a pull request at some point.

**Comment by theronic** [comment]
Also running into this where I'm trying to use throng from my main index.js, and it keeps starting the main function which hosts my web app. Not sure if this is throng or Cluster behaviour, but I would like to configure it, or at the very least instruct throng which arguments to pass to the main function.

**Comment by hunterloftis** [comment]
This is by design, as it's how [node's cluster](https://nodejs.org/api/cluster.html) module works.

- Master-process behavior should go into `master`.
- Worker-process behavior should go into `worker`.

Throng is a simple library to tackle the most-common use cases. It's outside of the scope of the library to expose all of the options available in the cluster module... for that level of control, use the cluster module itself.

That said, there's no need to use `exec` to specify worker behavior in another file. Just export the `worker` function in `worker.js`, require it in `index.js`, and pass it to throng.
