### ISSUE TITLE
Version 5.0 changelog

### ISSUE THREAD

**Issue by feimosi** [hunterloftis/throng#38]
I couldn't find any information on what has changed with the v5 release.
Are there any breaking changes?

**Comment by fiznool** [comment]
Here's a [comparison between v4 and v5](https://github.com/hunterloftis/throng/compare/7afef7ab5b9df8e02e49ab6095ccf2063fa32f89...e08ecbe056da301dccd74be8dc6bdb3f6494e50e). Looks like the main  changes are:

Steps up minimum node version from 4.x to 10.x (BREAKING)

Changes the options structure to the main `throng` function. Note that this appears to be backwards-compatible.

Before:

``` js
throng({
  workers: 4,
  master: startMaster,
  start: startWorker
});
```

After:

```
throng({ master, worker, count: 4 })
```

Adds a new `disconnect` function for shutting down a worker, instead of relying on `process.exit()`.

Before:

``` js
function startWorker(id) {
  console.log(`Started worker ${ id }`);
  process.on('SIGTERM', () => {
    console.log(`Worker ${ id } cleanup.`);
    console.log('(cleanup would happen here)');
    process.exit();
  });
}
```

After:

``` js
function worker(id, disconnect) {
  console.log(`Started worker ${ id }`)

  process.once('SIGTERM', shutdown)
  process.once('SIGINT', shutdown)
  function shutdown() {
    console.log(`Worker ${ id } exiting...`);
    disconnect()
  }
}
```

**Comment by feimosi** [comment]
@fiznool thanks a lot! I can confirm everything you wrote above. Surprisingly the options are backward-compatible.
I just wish the author would compose a least a very simple changelog.
